"""empty message

Revision ID: c61b66d06d9e
Revises: 
Create Date: 2020-11-07 14:47:01.000521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61b66d06d9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('still_in_cart', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('registration', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('registration', 'valid_until',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration', 'valid_until',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('registration', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_table('cart')
    # ### end Alembic commands ###
